version: '2.2'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - es-network

  kibana-new:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200  
#    ports:
#      - 5601:5601
#    networks:
#      - es-network
    depends_on:
      - node01

  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - kibana-new
#    networks:
#      - es-network
    ports:
      - 5601:5601
      
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.11.1
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    volumes:
      - /home/vaibhavg/Backup/Containers/load-balancer/Kibana/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
#    networks:
#      - es-network
    depends_on:
      - node01
    

volumes:
  es-data01:
    driver: local

#networks:
#  es-network:
#    driver: bridge
