# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  # Kubernetes master node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "alvistack/ubuntu-24.04"
    master.vm.network :private_network, ip: "192.168.57.101"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Set RAM to 1 GB
    end
    
    # Provisioning script for updating and upgrading
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end

  # Kubernetes node 1
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "alvistack/ubuntu-24.04"
    node1.vm.network :private_network, ip: "192.168.57.102"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Set RAM to 1 GB
    end

    # Provisioning script for updating and upgrading
    node1.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end

  # Kubernetes node2
  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.box = "alvistack/ubuntu-24.04"
    node2.vm.network :private_network, ip: "192.168.57.103"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Set RAM to 1 GB
    end

    # Provisioning script for updating and upgrading
    node2.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end


  # Optional: Global configuration for VirtualBox provider
  # This will apply if not overridden by specific VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
  end
end
