# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  # Jenkins Master Node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "alvistack/ubuntu-24.04"
    master.vm.network :private_network, ip: "192.168.56.101"
    
    # Prevent IP conflicts by assigning a fixed MAC address (Optional)
    master.vm.network :private_network, ip: "192.168.56.101", mac: "080027D14C66"

    # Provisioning script for updating and upgrading
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools default-jdk openjdk-17-jdk openjdk-8-jdk -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end

  # Node 1
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "alvistack/centos-8-stream"
    node1.vm.network :private_network, ip: "192.168.56.102"
    
    # Prevent IP conflicts by assigning a fixed MAC address (Optional)
    node1.vm.network :private_network, ip: "192.168.56.102", mac: "080027D14C67"

    # Provisioning script for updating and upgrading
    node1.vm.provision "shell", inline: <<-SHELL
      sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
      sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      sudo yum list all
      sudo yum install curl wget git vim screen htop -y
    SHELL
  end

  # SonarQube
  config.vm.define "sonar_qube" do |sonar|
    sonar.vm.hostname = "sonar"
    sonar.vm.box = "alvistack/ubuntu-24.04"
    sonar.vm.network :private_network, ip: "192.168.56.103"
    
    # Prevent IP conflicts by assigning a fixed MAC address (Optional)
    sonar.vm.network :private_network, ip: "192.168.56.103", mac: "080027D14C68"

    # Provisioning script for updating and upgrading
    sonar.vm.provision "shell", inline: <<-SHELL
      sudo apt install git vim screen htop net-tools -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end
end

