# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  # Jenkins Master Node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.network :private_network, ip: "192.168.56.101"
    
    # Provisioning script for updating and upgrading
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools default-jdk openjdk-17-jdk openjdk-8-jdk -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end

  # Slave and Nexus
  config.vm.define "node" do |node|
    node.vm.hostname = "node"
    node.vm.box = "bento/ubuntu-22.04"
    node.vm.network :private_network, ip: "192.168.56.102"

    # Provisioning script for updating and upgrading
    node.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools default-jdk openjdk-17-jdk openjdk-8-jdk -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end


  # SonarQube
  config.vm.define "sonar_qube" do |sonar|
    sonar.vm.hostname = "sonar"
    sonar.vm.box = "bento/ubuntu-22.04"
    sonar.vm.network :private_network, ip: "192.168.56.103"
    
    # Provisioning script for updating and upgrading
    sonar.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt install git vim screen htop net-tools default-jdk openjdk-17-jdk openjdk-8-jdk -y
      sudo add-apt-repository universe
      sudo add-apt-repository multiverse
      sudo apt update
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end
end

