version: '3.8'

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent
    restart: always
    environment:
      JENKINS_AGENT_NAME: "agent"
      JENKINS_URL: "http://jenkins:8080"
      JENKINS_SECRET: "<AGENT_SECRET>"
      JENKINS_AGENT_WORKDIR: "/home/jenkins/agent"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

volumes:
  jenkins-data:

networks:
  jenkins-net:
