#!/bin/bash

path=/media/vaibhavg/Backup/REPOS/StudyMaterial/scripts-learned
read -p "Please provide the file name that you want to create: " filename
touch $path/$filename\a.sh
chmod -R 777 $filename\a.sh
echo '#!/bin/bash' > $path/$filename\a.sh
echo '#Created date : ' `date +"%Y-%m-%d %r"` >> $path/$filename\a.sh
echo '#Modified date : ' >> $path/$filename\a.sh
echo '#Author: Vaibhav Gadhave' >> $path/$filename\a.sh
echo '#Start' >> $path/$filename\a.sh


echo '#End' >> $path/$filename\a.sh
sleep 1 
vim $path/$filename\a.sh

